theme="kaolin-dark"
#theme="saime-black-warm"

[editor]
line-number="relative"
bufferline="always"

rulers=[80]
popup-border="all"

[editor.cursor-shape]
insert="bar"
select="underline"

[editor.file-picker]
hidden=false
